inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.2
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - '*.gemspec'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'db/cache_schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
