version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-github_quality_test}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: ruby test.rb
    volumes:
      - .:/project
    depends_on:
      - postgres
    environment:
      DOCKER: "true"

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USERNAME: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-github_quality_test}

      PGHOST: postgres
      PGPORT: "5432"
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATABASE: ${POSTGRES_DB:-github_quality_test}

      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-github_quality_test}

volumes:
  pgdata:
