<%
  in_container = File.exist?("/.dockerenv") ||
                 (ENV["DOCKER"] && !ENV["DOCKER"].empty?)

  in_ci = (ENV["CI"] && !ENV["CI"].empty?)

  default_socket = "/var/run/postgresql"

  default_host =
    if in_container
      "postgres"
    elsif in_ci
      "127.0.0.1"
    else
      default_socket
    end

  default_user =
    if in_container || in_ci
      "postgres"
    else
      ENV["USER"]
    end
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", ENV.fetch("PGHOST", default_host)) %>
  port: <%= ENV.fetch("DB_PORT", ENV.fetch("PGPORT", 5432)) %>
  username: <%= ENV.fetch("DB_USERNAME", ENV.fetch("PGUSER", default_user)) %>
  password: <%= ENV["DB_PASSWORD"] || ENV["PGPASSWORD"] || ENV["POSTGRES_PASSWORD"] || (in_container ? "postgres" : nil) %>

development:
  <<: *default
  database: github_quality_development

test:
  <<: *default
  database: github_quality_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
